### ISSUE TITLE
Regarding build and db scripts

### ISSUE THREAD

**Issue by dipjyotighosh** [sonipks/auto-insurance#2]
Hi,
Do you have any build script for this?
Thanks.

**Comment by dipjyotighosh** [comment]
Please ignore

**Comment by sonipks** [comment]
Its long time since i created that. But you don't really need any build
script for that. Correct the DB path, and tables will be created
automatically based on the below property set in the hibernate-config.
*<prop key="hibernate.hbm2ddl.auto">update</prop>*

Just to let you know this project was created initially with plain jsp and
without any framework. I upgraded that to use struts and hibernate along
with spring. But, I believe there might be some minor errors to fix to make
it run. I left it like that so that it can be given as an assignment for
learning purposes to a few people.
